# Generated by Django 5.2.3 on 2025-06-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='password',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='username',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
            preserve_default=False,
        ),
    ]
