# Generated by Django 5.2.3 on 2025-07-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0002_rename_password_vendedor_apellido_and_more'),
        ('primera_app', '0003_avatar'),
    ]

    operations = [
    ]
