# Generated by Django 5.2.3 on 2025-07-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0004_merge_20250716_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatares/'),
        ),
    ]
